// frontend/src/page/admin.tsx
import { A } from "@solidjs/router";
import { Card, CardBody, CardHeader } from "@/component/core/card";

export function AdminPage() {
  return (
    <>
      <Card>
        <CardHeader>Admin tools</CardHeader>
        <CardBody>
          <ul>
            <li>
              <A href={"/new"}>Create a new game</A>
            </li>
            <li>
              <A href={"/invite"}>Invite a new user</A>
            </li>
          </ul>
        </CardBody>
      </Card>
    </>
  );
}

// frontend/src/routes/admin/+page.svelte
<script lang="ts">
	import Button from '$lib/components/core/Button.svelte';
	import Card from '$lib/components/core/Card.svelte';
	import CardColumn from '$lib/components/core/CardColumn.svelte';
	import CardHeader from '$lib/components/core/CardHeader.svelte';
	import CreateModal from './CreateModal.svelte';
	import InviteModal from './InviteModal.svelte';

	let showInviteModal = $state(false);
	let showCreateModal = $state(false);
</script>

<CardColumn>
	<Card>
		<CardHeader>Admin Controls</CardHeader>

		<ul>
			<li>
				<Button onclick={() => (showCreateModal = true)}>Create a game</Button>
			</li>
			<li>
				<Button onclick={() => (showInviteModal = true)}>Invite a user</Button>
			</li>
		</ul>
	</Card>
</CardColumn>

<InviteModal bind:show={showInviteModal} />
<CreateModal bind:show={showCreateModal} />

<style>
	ul {
		list-style: none;
		margin: 0;
		padding: 0;

		li {
			margin-top: 5px;
		}
	}
</style>
