// frontend/src/component/game/scoreTable.tsx
import { For, type JSX } from "solid-js";
import type { FrameLike } from "@/api/frame";
import styles from "./scoreTable.module.css";

type Props<P, A, C extends FrameLike & { total: number }> = {
  player(player: P, alias: A, rowIndex: number): JSX.Element;
  frame(cell: C, rowIndex: number, colIndex: number): JSX.Element;
  rows: {
    player: P;
    alias: A;
    frames: C[];
  }[];
};

export function ScoreTable<P, A, C extends FrameLike & { total: number }>(props: Props<P, A, C>) {
  return (
    <table class={styles.table}>
      <thead>
        <tr>
          <th scope="col">Player</th>
          <For each={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}>{(x) => <th scope="col">{x}</th>}</For>
          <th scope="col">Final</th>
        </tr>
      </thead>
      <tbody>
        <For each={props.rows}>
          {({ player, alias, frames }, row) => (
            <tr>
              <th scope="row">{props.player(player, alias, row())}</th>
              <For each={frames}>{(frame, col) => <td>{props.frame(frame, row(), col())}</td>}</For>
              <th>{frames[frames.length - 1].total}</th>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  );
}

// frontend/src/lib/components/game/ScoreTable.svelte
<script lang="ts" generics="P, A, F extends FrameLikeTotalled">
	import type { FrameLikeTotalled } from '$lib/api/frame';
	import type { Snippet } from 'svelte';
	import Table from '$lib/components/core/Table.svelte';
	interface Props<P, A, F> {
		player: Snippet<[P, A, number]>;
		frame: Snippet<[P, F, number, number]>;
		entries: {
			player: P;
			alias: A;
			frames: F[];
		}[];
	}

	const { player, frame, entries }: Props<P, A, F> = $props();
</script>

<Table>
	<thead>
		<tr>
			<th scope="col">Player</th>
			{#each [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as num (num)}
				<th scope="col">{num}</th>
			{/each}
			<th scope="col">Final</th>
		</tr>
	</thead>
	<tbody>
		{#each entries as entry, row (entry)}
			<tr>
				<th scope="row">{@render player(entry.player, entry.alias, row)}</th>
				{#each entry.frames as entryFrame, col (entryFrame)}
					<td>{@render frame(entry.player, entryFrame, row, col)}</td>
				{/each}
				<th>{entry.frames[entry.frames.length - 1].total}</th>
			</tr>
		{/each}
	</tbody>
</Table>
