// frontend/src/component/playerSelector.tsx
import { For } from "solid-js";
import { Player } from "@/api/player";
import { Select } from "./core/select";

type Props = {
  class?: string;
  player?: Player | null;
  setPlayer?: (player: Player) => void;
};

export function PlayerSelector(props: Props) {
  const onChange = (event: Event & { currentTarget: HTMLSelectElement }) => {
    const value = event.currentTarget.value;
    props.setPlayer?.(Player.getCached(value)!);
  };

  return (
    <>
      <Select onChange={onChange}>
        <For each={Player.getAllPlayers()}>
          {(player) => <option value={player.id}>{player.username}</option>}
        </For>
      </Select>
    </>
  );
}

// frontend/src/lib/components/player/PlayerSelector.svelte
<script lang="ts">
	import { Player } from '$lib/api/player';
	import Select from '$lib/components/core/Select.svelte';

	interface Props {
		value: Player | undefined;
	}

	let { value = $bindable() }: Props = $props();
</script>

<Select bind:value={() => value?.id ?? '', (v) => (value = Player.getCached(v)!)}>
	<option disabled hidden selected value="">Player...</option>
	{#await Player.getAllPlayers() then players}
		{#each players as player (player.id)}
			<option value={player.id}>{player.username}</option>
		{/each}
	{/await}
</Select>
